### ISSUE TITLE
I have been troubled by a question for a long time: What is 'avg_image.png,' and where can I obtain it

### ISSUE THREAD

**Issue by Youngchichi** [KumapowerLIU/CLCAE#2]

**Comment by KumapowerLIU** [comment]
You can find in this URL for ffhq:https://drive.google.com/drive/folders/19Q75nlaZ8KVdUd6C9s2y6c1cKXuB90TS 
For car: https://drive.google.com/drive/folders/17O9t74KlMHyrJ7Mx_jPJraae5BGXRGj7
